### ISSUE TITLE
aq-mode 4

### ISSUE THREAD

**Issue by realfinder** [jpsdr/x264#1]
hi
Is it possible to re-add --aq-mode 4 ?

**Comment by jpsdr** [comment]
Sorry, but i won't, and beside, when i talked with him, author himself discarded mode 4 because it hadn't a realy significant effect.

**Comment by realfinder** [comment]
it was there in last taro build https://astrataro.wordpress.com/2014/04/24/x264-rev2431-tmod/

**Comment by realfinder** [comment]
Writing library             : x264 core 142 r2431+42 c69a006 tMod [10-bit@all X86_64]
Encoding settings           : cabac=1 / ref=16 / deblock=1:0:-1 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / fade_compensate=0.50 / psy_rd=0.90:0.10 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=18 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / fgo=0 / bframes=16 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=1 / crf=16.0000 / qcomp=0.60 / qpmin=0:0:0 / qpmax=81:81:81 / qpstep=4 / ip_ratio=1.40 / aq=4:1.00 / aq-sensitivity=10.00 / aq-factor=1.00:1.00:1.00 / aq2=0 / aq3=0

see "aq=4:1.00"

**Comment by jpsdr** [comment]
Yes, but since the patch with aqmode 3/4 has been put on the official release with only aqmode 3, i'll stick with it, and not revert.

**Comment by realfinder** [comment]
I used to use 4 because I found it more balanced and gives suitable size not very big as the 3

It seems I'll stick in 2431 from taro

thank you anyway

**Comment by jpsdr** [comment]
If it's just the size, increase crf to reduce it.
For information, in case you don't know : 
http://forum.doom9.org/showpost.php?p=1692606&postcount=61
http://forum.doom9.org/showthread.php?t=170497

**Comment by realfinder** [comment]
I know

anyway, from a quick test with current mode 2 I see it results like mode 4 in taro, even in size almost the same

so I will use mode 2 if I use your build

Maybe off-topic, but (--acodec copy) with (--audiofile "path") give me error
"lavf [error]: could not open audio file
audio [error]: error initializing source filter!" 

and without (--audiofile "path") it encoding but not mux audio from original video like taro build did

"ffms [info]:
 Format    : matroska
 Codec     : h264
 PixFmt    : yuv420p10le
 Framerate : 24000/1001
 Timebase  : 1/1000000000
 Duration  : 0:23:40
lavf [error]: no decoder found for track 1
audio [error]: error initializing source filter!
ffms [info]: 1280x720p 1:1 @ 24000/1001 fps (vfr)
ffms [info]: color matrix: bt709"

**Comment by jpsdr** [comment]
I've tried to keep in the build the most of things, even those i don't need and i'm not interested in, but maybe one commit broke something, or, the lavf build i'm using is not compiled the same way taro build his own. Whatever case is, it's unforntunately out of my skill. For me, it's already a miracle i'm still able to make the actual builds keeping as maximum features as possible, but it seems that not 100% are  working. Sorry, for this issue, only hope is that one day taro will be back...

**Comment by jpsdr** [comment]
@realfinder 
Can you test your audio issues with the last release ? I've been able to compile ffmpeg and  ffms2 with more options, so it may work.

**Comment by realfinder** [comment]
yes, it work, thanks

**Comment by jpsdr** [comment]
Good to know. I can't guarantee it will work with all audios format, but at least there is improvement.

**Comment by kedaitinh12** [comment]
@realfinder, what aq mode you use now?? And aq-strength??
