### ISSUE TITLE
only Y signal，x264 has bug

### ISSUE THREAD

**Issue by kun-linux** [jpsdr/x264#12]
hi ；

when i set input signal is X264_CSP_I400，the app link libx264.a has  malloc error,fix this is add
    static const x264_csp_tab_t csp_tab[] =
    {
        [X264_CSP_I400] = { 1, { 256 * 1}, { 256 *  1} },
.......

when add this code,app is working,can y->h264.but has new issue,output has green color,like this:
![image](https://user-images.githubusercontent.com/50919178/58184441-af2ea180-7ce3-11e9-84e7-cbaa9e0a110b.png)

i dot know how to fix this??

**Comment by kun-linux** [comment]
@jpsdr

**Comment by kun-linux** [comment]
@Sparktank

**Comment by jpsdr** [comment]
Aouch... Unfortunately i'm afraid there is most likely nothing i'll be able to do... :(
With x264, i'm barely a compiler/builder (and user), but not a dev.
I'll try to see if i can do something, but don't have great expectation.
First, in what file and what line do you put your fix ?
Does this issue happen with standard version of x264 or only my t_mod build ?
Does it happen on these builds of mine : r2932, r2969, r2970 ?

**Comment by kun-linux** [comment]
thanks for you apply！
1：my x264 version is x264-snapshot-20190515-2245.
2：in common/base.c line 224
![image](https://user-images.githubusercontent.com/50919178/58217934-8df7a080-7d37-11e9-8afc-880233650932.png)

@jpsdr

**Comment by kun-linux** [comment]
here is my test code:

#include <stdio.h>
#include <stdlib.h>

#include "stdint.h"

#if defined ( __cplusplus)
extern "C"
{
#include "x264.h"
};
#else
#include "x264.h"
#endif


int main(int argc, char** argv)
{

	int ret;
	int y_size;
	int i,j;

	FILE* fp_src = fopen("./320x560_gray.yuv", "rb");
	FILE* fp_dst = fopen("/tmp/cuc_ieschool.h264", "wb");
	
	//if set 0, encode all frame
	int frame_num=200;
	int csp=X264_CSP_I400;
	int width=320,height=560;

	int iNal   = 0;
	x264_nal_t* pNals = NULL;
	x264_t* pHandle   = NULL;
	x264_picture_t* pPic_in  = (x264_picture_t*)malloc(sizeof(x264_picture_t));
	x264_picture_t* pPic_out = (x264_picture_t*)malloc(sizeof(x264_picture_t));
	x264_param_t* pParam = (x264_param_t*)malloc(sizeof(x264_param_t));
	
	//Check
	if(fp_src==NULL||fp_dst==NULL){
		printf("Error open files.\n");
		return -1;
	}
	//x264_param_default(pParam);
	if( x264_param_default_preset(pParam, "ultrafast", "fastdecode") < 0 )
	{
		printf("[%s, %d] ERROR ++++++++++++++++++++++++++\n", __FUNCTION__, __LINE__);
	}
	
	pParam->i_width   = width; 
	pParam->i_height  = height;
	pParam->i_log_level  = X264_LOG_INFO;
	pParam->i_csp=csp;
	x264_param_apply_profile(pParam, x264_profile_names[5]);
	pHandle = x264_encoder_open(pParam); 	
	x264_picture_init(pPic_out);
	ret = x264_picture_alloc(pPic_in, csp, pParam->i_width, pParam->i_height);

	y_size = pParam->i_width * pParam->i_height;
	
	//detect frame number
	if(frame_num==0){
		fseek(fp_src,0,SEEK_END);
		switch(csp){
		case X264_CSP_I444:frame_num=ftell(fp_src)/(y_size*3);break;
		case X264_CSP_I420:frame_num=ftell(fp_src)/(y_size*3/2);break;
		case X264_CSP_I400:frame_num=ftell(fp_src)/(y_size);break;
		default:printf("Colorspace Not Support.\n");return -1;
		}
		fseek(fp_src,0,SEEK_SET);
	}
	
	//Loop to Encode
	for( i=0;i<frame_num;i++){
		//printf("[%s, %d]\n", __FUNCTION__, __LINE__);
		switch(csp){
		case X264_CSP_I444:{
			fread(pPic_in->img.plane[0],y_size,1,fp_src);	//Y
			fread(pPic_in->img.plane[1],y_size,1,fp_src);	//U
			fread(pPic_in->img.plane[2],y_size,1,fp_src);	//V
			break;}
		case X264_CSP_I420:{
			fread(pPic_in->img.plane[0],y_size,1,fp_src);	//Y
			fread(pPic_in->img.plane[1],y_size/4,1,fp_src);	//U
			fread(pPic_in->img.plane[2],y_size/4,1,fp_src);	//V
			break;}
			
		case X264_CSP_I400:{
			fread(pPic_in->img.plane[0],y_size,1,fp_src);	//Y
			break;}
			
		default:{
			printf("Colorspace Not Support.\n");
			return -1;}
		}
		
		pPic_in->i_pts = i;
		ret = x264_encoder_encode(pHandle, &pNals, &iNal, pPic_in, pPic_out);
		if (ret< 0){
			printf("Error.\n");
			return -1;
		}	
		//printf("Succeed encode frame: %5d\n",i);
		for ( j = 0; j < iNal; ++j){
			 fwrite(pNals[j].p_payload, 1, pNals[j].i_payload, fp_dst);
		}
	
	}
	
	
	i=0;
	//flush encoder
	while(1){
		ret = x264_encoder_encode(pHandle, &pNals, &iNal, NULL, pPic_out);
		if(ret==0){
			break;
		}
		printf("Flush 1 frame.\n");
		for (j = 0; j < iNal; ++j){
			fwrite(pNals[j].p_payload, 1, pNals[j].i_payload, fp_dst);
		}
		i++;
	}
	
	x264_picture_clean(pPic_in);
	x264_encoder_close(pHandle);
	pHandle = NULL;

	free(pPic_in);
	free(pPic_out);
	free(pParam);

	fclose(fp_src);
	fclose(fp_dst);

	return 0;
}

**Comment by jpsdr** [comment]
Sorry, but if your issue is not specific to my release (meaning it's not me screwing things up with one of the several patches), but is an issue on the standard release, you're not in the right place.
You should try to post on doom9 forum, or mayb try here : [https://code.videolan.org/videolan/x264/](url)

**Comment by jpsdr** [comment]
I've opened the issue in the videolan, here : [https://code.videolan.org/videolan/x264/issues/2](url)

I suggest you continue on this other thread.

**Comment by kun-linux** [comment]
thanks for you help.today i make some test:

1：use X264_CSP_I400->X264_CSP_I420->H264 not X264_CSP_I400->H264 it works ,like this
	fread(pPic_in->img.plane[0],y_size,1,fp_src);	//Y
	memset(pPic_in->img.plane[1], 128, y_size/4);
	memset(pPic_in->img.plane[2], 128, y_size/4);

UV set default;

2：other way to X264_CSP_I400->X264_CSP_I420. i use ffmpeg lib sws_scale function to X264_CSP_I400->X264_CSP_I420 it also works.

but i dot know why  X264_CSP_I400->H264 rise this problem, and above way can result this problem.

i will concern videolan,thanks for you help again!!! @jpsdr

**Comment by MasterNobody** [comment]
Hi.

x264_picture_alloc change is OK and will be in next version of x264. As for green colors in X264_CSP_I400 it is bug in VLC and not in encoding (and probably not decoding but VLC output). ffplay decode and display it correctly (at least samples I made myself with kun-linux's test code).
