### ISSUE TITLE
Videoes encoded with the latest tMod doesn't play on a lot of TVs.

### ISSUE THREAD

**Issue by pcroland** [jpsdr/x264#13]
A lot of people complained that their TVs can't play videos from some groups. After some investigation it turned out that they all used the latest version of tMod. I don't know anything what can cause this issue but the latest tMod has a bug for sure.

**Comment by jpsdr** [comment]
Thanks, but without more information, i can't do anything. Unfortunately, even with information i'm not sure also to be able to do anything, i'm just someone who try to keep alive a build, i'm not an x264 dev. Doesn't mean i can't try...
I've used my last version to make a few Blu-Ray, burned, and play fine on stand-alone Blu-Ray player devices.
I need to know the exact command line used, and also what specific command line option trig the issue to check the specific patch used.
Also, does it trig the issue with the standard version ?
Is using just the previous version solve the issue ?
If i personnaly can't reproduce the issue (creating a file which not play on the few devices i have) it will be very difficult to test...

**Comment by pcroland** [comment]
The previous version works fine, the latest one was the one that caused a lot of complains in the comment section. It doesn't really matter what settings we use. The members that complained was not able to play any files encoded with the latest tMod on their TVs no matter which group it was from. The file that I sent out to some people to test was encoded with these settings:
`--level 4.1 --preset veryslow --no-fast-pskip --keyint 240 --colormatrix bt709 --vbv-maxrate 62500 --vbv-bufsize 78125 --merange 32 --bframes 10 --deblock -3,-3 --qcomp 0.65 --aq-mode 3 --aq-strength 0.8 --psy-rd 1.2 --ipratio 1.3 --crf 17.0`
crf and 2pass was also tested.
They didn't really specify what kind of TVs they use but it effects a small portion of downloaders. 2-10 comments about the issue/10000 downloads. (The actual number is probably higher)

**Comment by jpsdr** [comment]
Version r2969 works fine, but r2970 produces the issue, that's it ?
From the command line, there is nothing specific to the tMod version patches, so there is no realy need to uses the tMod version. Have you tested with official r2970 release ? Unfortunately for me it's the worst case. If there was some specific patch used, i could have checked it, but here...
The only thing i can do is triple check again all my patches integration, this will take a long time because i don't have a lot of time here. But if i found nothing (the risk is great), i unfortunately not be able to do anything. I'm not an x264 dev, just someone who try to keep this build alive without screewing things (but it seems it fails... :( ).
Can you provide me an email where i can send you information about my private server we can use to exchange file ?

**Comment by pcroland** [comment]
If you compile a vanilla x264 I could send out a twst encode to the affected users.

**Comment by jpsdr** [comment]
Why vanilla ? Just getting an official build release. Nevertheless, something bothering me. Unless i misunderstand things, according p293 of T-REC-H.264-201704-I!!PDF-E, for level 4.1 the max bitrate is 50000, not 62500, wich means maybe it produces out of specs stream. But as i'm not sure, i'll ask confirmation on doom9.

I'll contact you when back home to provide my server informations, and being able to make some small encode test. Or, provide me the input file you've used to make encode test (when you'll have server information... ^_^).

**Comment by pcroland** [comment]
The max bitrate is 62500 for 4.1, but I tested lower values just in case. And it doesn't really matter because the files were low resolution so the bitrate didn't go that high anyway.

**Comment by pcroland** [comment]
If you have Telegram you can also text me there (@pcroland). It would be faster there and we could send files easily :D

**Comment by jpsdr** [comment]
No, unfortunately i don't have. I've send you an email.

**Comment by jpsdr** [comment]
After tests, the issue also occurs on encode done with official build r2969, so it's not related to the tMod version.
