### ISSUE TITLE
This binary is unredistributable!

### ISSUE THREAD

**Issue by lordmulder** [jpsdr/x264#14]
FYI: One of my users just pointed out that, apparently, you are distributing "non-free" binaries:

```
x264_x64.t_mod.exe --version

x264 0.159.2991+49 524a90c t_mod_New [0-bit@all X86_64]
(libswscale 5.5.100)
(libavformat 58.29.100)
(ffmpegsource 2.31.0.0)
built on Dec 21 2019, gcc: 9.2.1 20191212
x264 configuration: --chroma-format=all--disable-opencl
libx264 configuration: --chroma-format=all--disable-opencl
x264 license: Non-Free
libswscale/libavformat/ffmpegsource license: nonfree and unredistributable
WARNING: This binary is unredistributable!
```

**Comment by jpsdr** [comment]
Ah... I'll check this when i have time, and make another release even more when i have more time...

**Comment by jpsdr** [comment]
Unfortunately, i got ill and have to stay at home. This, unexpectedly, provided me a lot sonner the necessary time to check this.
New release made and should be fine, i think.

**Comment by lordmulder** [comment]
👍
