### ISSUE TITLE
Several fprofiled build

### ISSUE THREAD

**Issue by Ichunjo** [jpsdr/x264#18]
I just want to know what's the difference between the three builds. 
I made test encodes and the results and the time were pretty similar...

**Comment by jpsdr** [comment]
Fortunately are the same, the opposite would have been a big problem.
It's just build with different GCC threading model (how the multithreading is handled).
In speed, from my test you have mcf faster than win32 faster than posix.
But each "faster step" was something like 2 minutes on a 2h encode.
The several versions are if for some reason, people would like to use a specific threading model, or if for any unknow (and theoricaly shouldn't happen) reason someone have trouble with one specific version, he still have two others possibilities.

**Comment by Ichunjo** [comment]
Oh I see! Very thanks for the explanation!
