### ISSUE TITLE
tmod build, "writing library" field is incorrect

### ISSUE THREAD

**Issue by Meru** [jpsdr/x264#2]
Hi. Your tmod build seem to be working fine, but there is one cosmetic issue.  it writes into h264 stream that the version is r0+2586, which is obviously not correct. It should be r2586+X+Y where X/Y are modifications on top of the vanilla codebase.

**Comment by jpsdr** [comment]
I've noticed, but i've no idea why. As it's purely cosmetic, i don't intend to waste time figuring out this. It  doesn't mean i'll not fix it if by any luck one day i'll know how to fix, and fix is easy.

**Comment by Meru** [comment]
Well, some GUIs don't work because of this. Like Lord Mulder's launcher. But yeah, I don't use GUIs myself, just thought I'll report it.
Might have something to do with correct rebasing changes on top of the vanilla codebase. I remember Taro mentioned something like that one day.

**Comment by jpsdr** [comment]
Issue fixed with last commit, as it can be seen, it was easy and just a silly typo.
