### ISSUE TITLE
--audiofile does not support comma in argument

### ISSUE THREAD

**Issue by mbassiouny33** [jpsdr/x264#23]
Hi there,

I ran into an issue with --audiofile argument
```

x264_32_tMod-8bit-all.exe --crf 22   --tune animation --preset fast --acodec copy --audiofile "input/file,name.mkv"  -o  "out/file,name.mkv" "input/file,name.mkv"   
```

this will trigger

> options [error]: Too many options given                               
> audio [error]: error initializing source filter!

Since I am using `-acodec copy` from same source I can get away without specifying --audiofile

```

x264_32_tMod-8bit-all.exe --crf 22   --tune animation --preset fast --acodec copy  -o  "out/file,name.mkv" "input/file,name.mkv"   
```
and this works perfectly fine...

**Comment by jpsdr** [comment]
... Sorry for late response, probably missed the notification.
Unfortunately, i'm juste building the t_mod version, not providing any support or fix of any kind.
