### ISSUE TITLE
Could you please add tMod in the `Writing library`?

### ISSUE THREAD

**Issue by pcroland** [jpsdr/x264#25]
It would be nice if mediainfo would show
```
Writing library: x264 core 164 r3106+49 tMod 2efe26b devel [(8 & 10)-bit@all X86_64]
```
instead of
```
Writing library: x264 core 164 r3106+49 2efe26b devel [(8 & 10)-bit@all X86_64]
```

Edit: nevermind, it's a fork of your version that doesn't have tMod in it. Altough i would switch it back from `t_mod_New` to just `tMod`.

**Comment by jpsdr** [comment]
Ok, so i close.
