### ISSUE TITLE
lcevc support 

### ISSUE THREAD

**Issue by vslmc** [jpsdr/x264#26]
I would like to know if the additional layer encoding of lcevc could be implemented. 

To be clear, one could call it another codec which uses avc encoded frames.

This may not be the scope of this repo , nonetheless I think its a good alternative albeit usable with software decoder only (afaik)

V-Nova distributes a ffmpeg build (needs to be made public but isn't) with modified libx264 (also GPL I believe) ; sadly it's for company developer only (register wall)

**Comment by jpsdr** [comment]
Sorry, this is the wrong place for asking this, i'm just doing the build of x264, i'm not a dev on it.

**Comment by vslmc** [comment]
I thought this repo also includes patches/diffs not used in the official version ? Maybe I was wrong about that

If you think this repo shouldn't make such changes , where should I ask this instead ?

Thank you for your respond

**Comment by jpsdr** [comment]
I don't make the patches, just include them.
