### ISSUE TITLE
Add support utf8 file name

### ISSUE THREAD

**Issue by kedaitinh12** [jpsdr/x264#27]
I tried to encode this file but got an error: x264: could not open the input file. Can you add support utf8 file name?
https://drive.google.com/file/d/1VAcp5b28eCjlqwZoNxd0z3Ge4R3pRbJK/view?usp=sharing

**Comment by jpsdr** [comment]
Didn't see this one.
Sorry, i'm just building/compiling, i don't do this kind of things, and honestly i have no idea how to do this.

**Comment by kedaitinh12** [comment]
> Didn't see this one. Sorry, i'm just building/compiling, i don't do this kind of things, and honestly i have no idea how to do this.

I saw x265 support utf-8 very long, you can base x265 code and do it for x264
