### ISSUE TITLE
About the output on cmd

### ISSUE THREAD

**Issue by tuanden0** [jpsdr/x264#4]
Dear Sir,

Can you make the cli output monitor of cmd just in 1 line like x264 Kmod? It's hard to check the elapsed time when x264 start to the end.
Sorry for my bad English.

Thank You.

**Comment by realfinder** [comment]
same here, add option that control how cli will be?

**Comment by jpsdr** [comment]
Sorry, no idea how to do this kind of thing, and not interested in spending time on this.

**Comment by TheDonCorleone** [comment]
just pull the cmd window on the right side a bit over the original size, and it'll compact the monitoring to a single line. :)

**Comment by bex39** [comment]
I think it's already included in tmod / t_mod_custom version (via r2204 style progress indicator patch), have you tried to add **--stylish** on x264 paramater?

**Comment by tuanden0** [comment]
@bex39 
Thank you very much!
