### ISSUE TITLE
[req] -opencl add suppoprt

### ISSUE THREAD

**Issue by shikulja** [jpsdr/x264#7]
Very lack of support for opencl, which already exists on almost all video cards, and significantly increases the speed of video encoding

**Comment by jpsdr** [comment]
Sorry, but i won't. I'm not interested in, it's more difficult to build with open-cl and as i'm not interested in it, i don't intend to spend time for this, and from what i remember having read when open-cl was implemented, there is a slight quality loss compared with no open-cl with the exact encode parameters (so this is why i'm not interested in).
